# Generated by Django 6.0.5 on 2026-05-19 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField()),
                ('issue_since', models.CharField(blank=True, max_length=50)),
                ('affects_all_devices', models.BooleanField(default=False)),
                ('only_wifi', models.BooleanField(default=False)),
                ('specific_hours', models.BooleanField(default=False)),
                ('attachment', models.ImageField(blank=True, null=True, upload_to='complaint_attachments/')),
                ('ai_category', models.CharField(blank=True, choices=[('speed_issue', 'Speed Issue'), ('router', 'Router'), ('outage', 'Outage'), ('billing', 'Billing'), ('installation', 'Installation')], max_length=50)),
                ('ai_priority', models.CharField(blank=True, choices=[('urgent', 'Urgent'), ('medium', 'Medium'), ('low', 'Low')], max_length=20)),
                ('ai_confidence', models.FloatField(blank=True, null=True)),
                ('ai_suggested_action', models.TextField(blank=True)),
                ('ai_estimated_resolution', models.CharField(blank=True, max_length=100)),
                ('ai_analyzed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('ai_analyzed', 'AI Analyzed'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('resolved', 'Resolved')], default='submitted', max_length=30)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'complaints',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComplaintNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'complaint_notes',
            },
        ),
    ]
